### PR TITLE
CLI: List comand enhancement 

### PR DESCRIPTION
**Pull request by Strongleong**
Fixes issue #32

### CODE REVIEW

**Comment by romibi** [comment]
Not sure i like `-n` for suppressing error output …
As soon as we have another "noWhatever" option the n doesn't make sense anymore …
But we already used "s" (as in silent) and "q" (as in quiet) for other arguments …
maybe skip having a short version? Or do you have an idea for a better one?

Also i think we normalized the arguments words to camelCase.
I'd preffer `noErrorOutput`.

Apart from this: looks good.

**Comment by Strongleong** [comment]
I agree about `-n`. I can't come up with something better. I think is not a bad idea to remove short version of this flag. 
About camelCase I am not so sure. Having camelCase --flags is just do not clicks in my head, can't explain it better.

**Comment by romibi** [comment]
> I agree about -n. I can't come up with something better. I think is not a bad idea to remove short version of this flag.

Ok then we drop the short version.

> About camelCase I am not so sure. Having camelCase --flags is just do not clicks in my head, can't explain it better.

I understand what you mean … true, hyphenated cli arguments are more common.
But in #13 we switched the few cli arguments that were hyphenated to camelCase to match the others.
Maybe we should have used hyphenated arguments instead?

Should we change all arguments again?
But as soon as someone starts to use it in their scripts we should try to avoid to change it anymore.
What do you think?

**Comment by Strongleong** [comment]
Well, I already started using it in my scripts 😅 
But I check version of ScrapPacketExplorer in my scripts. 
We can change arguments since last releast version is 0.3.1, i.e. not stable. But in another PR

**Pull request merged**
